import { Squada_One } from "next/font/google";
import { Signika } from "next/font/google";
import "./globals.css";

const squadaOne = Squada_One({
  variable: "--font-squadaOne",
  subsets: ["latin"],
  weight: "400",
});

const signika = Signika({
  variable: "--font-signika",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "StokAja!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${squadaOne.variable} ${signika.variable} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}